FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY /build /code/
RUN mkdir /code/build_landing/
COPY /build_landing /code/build_landing/
RUN mkdir /code/sitdiwn/
COPY /sitdown /code/sitdown/
COPY nginx.conf /etc/nginx/conf.d