# Generated by Django 4.1 on 2022-08-27 08:54

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0002_alter_resume_avatar_alter_resume_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatido',
            old_name='short_description',
            new_name='des',
        ),
        migrations.AddField(
            model_name='whatido',
            name='bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=400, samples=None),
        ),
        migrations.AddField(
            model_name='whatido',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=400, samples=None),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='workingskills',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_builder.resume'),
        ),
    ]
