# Generated by Django 4.1 on 2022-08-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0003_rename_short_description_whatido_des_whatido_bg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatido',
            name='color',
        ),
    ]
