# Generated by Django 4.1 on 2022-08-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0004_remove_whatido_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='short_description',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='short_description',
            new_name='place',
        ),
    ]
