# Generated by Django 4.1 on 2022-08-27 09:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0005_rename_short_description_education_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingskills',
            name='color',
            field=colorfield.fields.ColorField(default='#5185D4', image_field=None, max_length=400, samples=None),
        ),
    ]
