# Generated by Django 4.1 on 2022-08-27 10:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0006_workingskills_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=400, samples=None),
        ),
        migrations.AddField(
            model_name='experience',
            name='bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=400, samples=None),
        ),
    ]
