# Generated by Django 4.1 on 2022-08-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0007_education_bg_experience_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatido',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
