# Generated by Django 4.1 on 2022-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0008_alter_whatido_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50),
        ),
    ]
