# Generated by Django 4.1 on 2022-08-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0009_resume_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='private_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='private_token_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='private_token_lifetime',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
