# Generated by Django 4.1 on 2022-08-28 10:29

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0010_resume_is_private_resume_private_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='can_download_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='include_blogs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='workingskills',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('img_small', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('bg', colorfield.fields.ColorField(default='#EEFBFF', image_field=None, max_length=18, samples=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
