# Generated by Django 4.1 on 2022-08-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0011_resume_can_download_cv_resume_include_blogs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img_small',
        ),
    ]
