# Generated by Django 4.1 on 2022-08-29 13:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0014_blog_img_big_blog_img_small_alter_resume_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
