# Generated by Django 4.1 on 2022-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0015_resume_avatar_thumbnail_alter_resume_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='des',
            field=models.TextField(),
        ),
    ]
