# Generated by Django 4.1 on 2022-09-17 10:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0016_alter_education_place_alter_education_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='bg',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=400, samples=None, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='des',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
