# Generated by Django 4.1 on 2022-09-17 11:04

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0017_alter_about_short_description_alter_whatido_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(max_length=20)),
                ('color', colorfield.fields.ColorField(default='#5185D4', image_field=None, max_length=400, samples=None)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv_builder.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
