# Generated by Django 4.1 on 2022-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0018_resume_is_active_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='knowledge',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='whatido',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workingskills',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='resume',
            name='language_used',
            field=models.CharField(choices=[('en', 'En'), ('ro', 'Ro')], default='en', max_length=20),
        ),
    ]
