# Generated by Django 5.2.7 on 2025-10-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0019_alter_about_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='step',
            field=models.CharField(choices=[('started', 'Started'), ('step_1', 'Step 1'), ('step_2', 'Step 2'), ('step_3', 'Step 3'), ('completed', 'Completed')], default='started', max_length=50),
        ),
    ]
