# Generated by Django 5.2.7 on 2025-10-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0020_resume_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='from_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='from_date',
            new_name='start_date',
        ),
    ]
