# Generated by Django 5.2.7 on 2025-10-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0021_rename_from_date_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='resume',
            name='step',
            field=models.CharField(choices=[('started', 'Started'), ('step_1', 'Step 1'), ('step_2', 'Step 2'), ('step_3', 'Step 3'), ('step_4', 'Step 4'), ('theme', 'Theme'), ('completed', 'Completed')], default='started', max_length=50),
        ),
    ]
