# Generated by Django 5.2.7 on 2025-10-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0022_resume_config_alter_resume_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatido',
            old_name='des',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='education',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='language',
            name='color',
        ),
        migrations.RemoveField(
            model_name='whatido',
            name='bg',
        ),
        migrations.RemoveField(
            model_name='whatido',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='workingskills',
            name='color',
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
