# Generated by Django 5.2.7 on 2025-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0023_rename_des_whatido_description_remove_blog_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
